cgpt/urls.py
from django.urls import path
from . import views


app_name = 'cgpt'

urlpatterns = [
    path('', views.cgpt, name='cgpt'),
    path('recommend_keyword/', views.recommend_keyword, name='recommend_keyword'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('mypage/<int:user_id>', views.mypage, name='mypage'),
]

course_web_prj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('place/', include("place.urls")),
    path('restaurant/', include("restaurant.urls")),
    path('', include("home.urls")),
    path('common/', include('common.urls')),
    path('cgpt/', include('cgpt.urls')),
]

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('choose/', views.choose, name='choose'),
]

place/urls.py
from django.urls import path
from . import views

app_name = 'place'
urlpatterns = [
    path('place_category/', views.place_category, name='place_category'),  # 장소 카테고리 선택 화면으로 가기
    path('references/', views.references, name='references'),  # 나들이 장소 선택 화면으로 가기
    path('afterpick/', views.afterpick, name='afterpick'),  # 선택한 장소의 정보 확인하는 화면으로 가기
    path('set_keyword/', views.set_keyword, name='set_keyword'),
]

home/views.py
from django.shortcuts import render

# 랜더 함수를 통해 home 화면 출력
def home(request):
    return render(request,'home/home.html')

# 랜더 함수를 통해 home 화면 출력
def choose(request):
    return render(request,'home/choose.html')

home/templates/home/choose.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% load static %}
    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/favicon/apple-touch-icon.png' %}" />
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/favicon/favicon-32x32.png' %}" />
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/favicon/favicon-16x16.png' %}" />
    <link rel="manifest" href="{% static 'assets/favicon/manifest.json' %}" />
    <link rel="mask-icon" href="{% static 'assets/favicon/safari-pinned-tab.svg' %}" color="#5bbad5" />
    <link rel="shortcut icon" href="{% static 'assets/favicon/favicon.ico' %}" />
    <meta name="msapplication-config" content="{% static 'assets/favicon/browserconfig.xml' %}" />
    <meta name="theme-color" content="#ffffff" />
    
    <!-- Libs CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/libs.bundle.css' %}" />
    
    <!-- Theme CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/theme.bundle.css' %}" />
    
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,700;0,900;1,400;1,700;1,900&family=Playfair+Display:ital,wght@0,400;0,700;1,400;1,700&display=swap"
      rel="stylesheet"
    />
    
    <!-- Map -->
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css" />
    
    <!-- 
      Color mode switch
      - For demonstration purposes only
      - If you do not have the possibility to store user preferences on the backend, I highly recommend switching to a media query implementation: https://getbootstrap.com/docs/5.3/customize/color-modes/#building-with-sass
    -->
    <script>
      (() => {
        window.addEventListener('DOMContentLoaded', () => {
          const colorModeSwitch = document.getElementById('colorModeSwitch');
          if (colorModeSwitch) {
            colorModeSwitch.addEventListener('change', () => {
              document.body.setAttribute('data-bs-theme', colorModeSwitch.checked ? 'dark' : 'light');
            });
          }
        });
      })();
    </script>
    
    <!-- Title -->
    <title>photo walk & eat &amp; fourhands</title>
   
    <link href="{% static 'button_space.css' %}" rel="stylesheet"> <!-- 커스텀 CSS 파일 링크 -->
  </head>
  <body>
    <!-- NAVBAR -->
    <nav class="navbar navbar-dark navbar-expand-lg navbar-togglable fixed-top">
      <div class="container">
        <!-- Navbar brand (mobile) -->
        <a class="navbar-brand d-lg-none" href="{% url 'home:home' %}">photo walk & eat</a>
    
        <!-- Navbar toggler -->
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarCollapse"
          aria-controls="navbarCollapse"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navbar brand -->
        <a class="navbar-brand d-none d-lg-flex mx-lg-auto" href="{% url 'home:home' %}"> photo walk & eat </a>

        <!-- Navbar collapse -->
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a></li>
      
          {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'common:mypage' user.id %}">마이페이지</a></li>
          <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'common:logout' %}">로그아웃</a></li>
          {% else %}
          <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'common:login' %}">로그인</a></li>
          <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'common:signup' %}">회원가입</a></li>
          {% endif %}
        </ul>

          <!-- Color mode -->
          <div class="form-check form-switch form-switch-color-mode ms-lg-3">
            <input class="form-check-input" type="checkbox" role="switch" id="colorModeSwitch" />
            <label class="form-check-label" for="colodeModeSwitch"></label>
          </div>
        </div>
      </div>
  </nav>
   <!-- HEADER -->
   <header data-jarallax data-speed=".8" style="background-image: url({% static 'assets/img/35.jpg' %})">
  
    <div class="pt-8 pb-6 pt-md-10 pb-md-9 bg-black bg-opacity-50">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-12 col-md-8 col-lg-6 text-center">
            <!-- Heading -->
            <h1 class="display-6 fw-bold text-white">choose your place category</h1>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- choose-->
  <style>
    body, html {
        height: 100%;
        margin: 0;
        font-family: Arial, sans-serif;
    }
    .button-container {
        text-align: center;
        margin-bottom: 300px;
    }
    button {
        padding: 15px 30px;
        margin: 10px;
        font-size: 16px;
        cursor: pointer;
        border: none;
        border-radius: 5px;
    }

    .subheading {
      margin-bottom: 100px;
    }  
    .category-button {
        background-color: #4CAF50;
        color: white;
    }
    .recommendation-button {
        background-color: #008CBA;
        color: white;

    }
  </style>
  
<section class="pt-8 pt-md-9">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-8 col-lg-6 text-center">
        <!-- Heading -->
        <h2 class="fw-bold mb-8">출사 테마 선택 방법</h2>

        <!-- Subheading -->
        <p class="subheading">마땅한 테마가 떠오르지 않는다면 AI에게 물어보세요! 또는 직접 카테고리를 확인하고 선택할 수 있습니다. </p>
      </div>
    </div>

    <div class="button-container">
      <button class="category-button" onclick="window.location.href='{% url 'place:place_category' %}'">카테고리 선택하기</button>
      <button class="recommendation-button" onclick="window.location.href='{% url 'cgpt:cgpt' %}'">챗봇에게 추천받기</button>
  </div>
  </div>
</section>

  <!-- FOOTER -->
  <footer class="py-7 py-md-9 bg-black">
    <div class="container px-4">
      <div class="row gx-7">
        <div class="col-sm-4">
          <!-- Heading -->
          <h5 class="text-xs text-primary">About Us</h5>
  
          <!-- Text -->
          <p class="mb-6">
            우리는 포핸즈, 소프트웨어 공학 설계에서 출발한 프로젝트 팀으로 2024 1학기 학습공동체의 스터디 팀으로 지원함.
        </div>
        <div class="col-sm-4">
          <!-- Heading -->
          <h5 class="text-xs text-primary">Contact info</h5>
  
          <!-- List -->
          <ul class="list-unstyled mb-6">
            <li class="d-flex mb-2">
              <div class="fas fa-map-marker-alt me-3 mt-2 fs-sm"></div>
              서울특별시 동대문구 서울시립대로 163 <br>서울시립대학교 과학기술관
            </li>
            
            <li class="d-flex">
              <div class="far fa-envelope me-3 mt-2 fs-sm"></div>
              <a href="mailto:admin@domain.com">4handsgpt@gmail.com</a>
            </li>
          </ul>
        </div>

      <div class="row">
        <div class="col-12">
          <!-- Copyright -->
          <div class="d-flex align-items-center">
            <hr class="hr-sm me-3" style="height: 1px" />
            &copy; 2024 fourhands. All rights reserved.
          </div>
        </div>
      </div>
    </div>
  </footer>

    <!-- JAVASCRIPT -->
    <!-- Vendor JS -->
    <script src="{% static 'assets/js/vendor.bundle.js' %}"></script>
    
    <!-- Theme JS -->
    <script src="{% static 'assets/js/theme.bundle.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>