cgpt/urls.py
from django.urls import path
from . import views


app_name = 'cgpt'

urlpatterns = [
    path('', views.cgpt, name='cgpt'),
    path('recommend_keyword/', views.recommend_keyword, name='recommend_keyword'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('mypage/<int:user_id>', views.mypage, name='mypage'),
]

course_web_prj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('place/', include("place.urls")),
    path('restaurant/', include("restaurant.urls")),
    path('', include("home.urls")),
    path('common/', include('common.urls')),
    path('cgpt/', include('cgpt.urls')),
]

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('choose/', views.choose, name='choose'),
]

templates/includes/header.html
<header class="masthead">
    <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
        <div class="d-flex justify-content-center">
            <div class="text-center">
                <!-- 로그인을 했다면 시작 버튼, 로그아웃 버튼 생성 -->
                {% if user.is_authenticated %}
                <a class="btn btn-success" href="{% url 'home:choose' %}">시작하기</a>
                <a class="btn btn-warning" href="{% url 'common:logout' %}">로그아웃 ({{ user.username }})</a>

                <!-- 로그인을 안했다면 시작 버튼, 로그인 버튼, 회원가입 버튼 생성 -->
                {% else %}
                <a class="btn btn-success" href="{% url 'home:choose' %}">시작하기</a>
                <a class="btn btn-success" href="{% url 'common:login' %}">로그인</a>
                <a class="btn btn-primary" href="{% url 'common:signup' %}">회원가입</a>
                {% endif %}
            </div>
        </div>
    </div>
</header>

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home:home' %}">Photo - walk & eat</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'common:mypage' user.id %}">마이페이지</a></li>
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'common:logout' %}">로그아웃 ({{ user.username }})</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'common:login' %}">로그인</a></li>
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'common:signup' %}">회원가입</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>